apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: actions-runner-system
type: Opaque
data:
  github_app_id: BASE64-ENCODED-APP-ID
  github_app_installation_id: BASE64-ENCODED-APP-INSTALLATION-ID
  github_app_private_key: BASE64-ENCODED-APP-PRIVATE-KEY
