---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: edx-platform-ci-runner-deployment
  namespace: actions-runner-system
spec:
  template:
    spec:
      # this should be updated to edx/edx-platform
      repository: mraarif/edx-platform
      # this should also point to runner image hosted under edX's dockerhub
      image: mraarif/edx-platform-gha-ci:1.0
      # dockerdWithinRunnerContainer: true
      # env:
      #   - name: GITHUB_TOKEN
      #     valueFrom:
      #       secretKeyRef:
      #         name: controller-manager
      #         key: github_token
      resources:
        requests:
          cpu: "2.0"
          memory: "4Gi"

      # sidecarContainers:
      #   - name: mongo
      #     image: mongo:3.6.17
      #     container_name: "mongo"
      #     ports:
      #       - containerPort: 27017
      #     command: ["mongod"]
      #     args: ["--nojournal", "--storageEngine", "wiredTiger"]
      #     volumeMounts:
      #       - mountPath: /data/db
      #         name: mongo-data
      #     hostname: mongo.devstack.edx
      #     restartPolicy: Always
      # volumes:
      #   - name: mongo-data
      #     emptyDir: {}

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: edx-platform-ci-runner-deployment-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: edx-platform-ci-runner-deployment
  minReplicas: 2
  maxReplicas: 60
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: "0.75"
      scaleDownThreshold: "0.3"
      scaleUpAdjustment: 2
      scaleDownAdjustment: 1
  scaleUpTriggers:
    - githubEvent:
        pullRequest:
          types: ["synchronize"]
          branches:
            - "**"
      amount: 12
      duration: "15m"
    - githubEvent:
        push:
          branches: ["master"]
      amount: 12
      duration: "15m"
