---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: edx-platform-ci-runner-deployment
  namespace: actions-runner-system
spec:
  template:
    spec:
      repository: edx/edx-platform
      # this should also point to runner image hosted under edX's dockerhub
      image: mraarif/edx-platform-gha-ci:1.7
      resources:
        requests:
          cpu: "2.0"
          memory: "4Gi"

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: edx-platform-ci-runner-deployment-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: edx-platform-ci-runner-deployment
  scaleDownDelaySecondsAfterScaleOut: 60
  minReplicas: 12
  maxReplicas: 72
#  scaleUpTriggers:
#    - githubEvent: {}
#      duration: "20m"
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - edx/edx-platform
  - type: PercentageRunnersBusy
    scaleUpThreshold: "0.75"
    scaleDownThreshold: "0.3"
    scaleUpAdjustment: 2
    scaleDownAdjustment: 1
#  scaleUpTriggers:
#  - githubEvent:
#      checkRun:
#        types: ["created", "rerequested"]
#        status: "queued"
#    amount: 12
#    duration: "20m"
#  - githubEvent:
#      pullRequest:
#        types: ["opened", "synchronize", "reopened"]
#    amount: 12
#    duration: "20m"
# - githubEvent:
#     push:
#       branches: ["master"]
#   amount: 12
#   duration: "20m"
