# authSecret:
#   create: true
#   github_app_id:
#   github_app_installation_id:
#   github_app_private_key: |
#

githubWebhookServer:
  enabled: true
  service:
    type: NodePort
    ports:
      - port: 80
        targetPort: http
        protocol: TCP
        name: http
        nodePort: 32080
